---
###
# Pulls the code from a remote Git repository, configures the web application,
# creates a virtualenv, and collects static assets
#

# - name: install known_hosts file to access GitHub
#   copy: src=ssh_conf/known_hosts dest={{ssh_dir}}/known_hosts

- name: checkout latest web app code
  git: repo={{ git_repo }} dest={{ app_checkout_path }}

- name: check if virtualenv already exists
  stat: path={{ virtualenv_path }}
  register: venv_dir

- name: create virtualenv for Django web application
  shell: virtualenv {{virtualenv_dir}}
  when: venv_dir.stat.isdir is not defined

- name: install web application dependencies listed in requirements.txt
  pip: requirements={{requirements_file}} virtualenv={{virtualenv_path}}

- name: Django collectstatic
  django_manage: command=collectstatic
                 app_path={{ app_checkout_path }}
                 virtualenv={{ virtualenv_path }}
                 settings={{ settings_file }}
  environment: django_env_vars

- name: Django syncdb
  django_manage: command=syncdb
                 app_path={{ app_checkout_path }}
                 virtualenv={{ virtualenv_path }}
                 settings={{ settings_file }}
  environment: django_env_vars
  when: sync_db

- name: Django migrate
  django_manage: command=migrate
                 app_path={{ app_checkout_path }}
                 virtualenv={{ virtualenv_path }}
                 settings={{ settings_file }}
  environment: django_env_vars
