---
###
# Pulls the code from a remote Git repository, configures the web application,
# creates a virtualenv, and collects static assets
#

- include: django_setup_prepare.yml

- include: django_setup_standard.yml

- include: django_setup_custom.yml
