---
# This playbook contains common plays that will be run on all nodes.

- name: ensure app server packages are installed
  apt: pkg={{item}} state=present
  sudo: yes
  with_items:
    - git
    - python-pip 
    - python-dev
    - libpq-dev
    - python-virtualenv
    - nginx
    - supervisor
    - postgresql-client-common
    - postgresql-client

- name: ensure celery related packages are installed
  apt: pkg={{item}} state=present
  sudo: yes
  with_items:
    - rabbitmq-server
  when: install_celery

- name: install custom packages
  apt: pkg={{item}} state=present
  sudo: yes
  with_items: custom_app_pkg
  when: item != ''

- include: config_user_permissions.yml

- include: config_django_project.yml

- include: config_gunicorn.yml

- include: config_celery.yml

- include: config_supervisor.yml

- include: config_nginx.yml
