---

# TODO check if the restart runs properly
- name: restart nginx
  service: name=nginx state=restarted
  sudo: yes

- name: restart supervisor
  service: name=supervisor state=restarted
  sudo: yes

- name: run gunicorn
  command: bash {{ webapps_home }}bin/gunicorn_start.sh
  sudo: yes
