---

# TODO check if the restart runs properly
- name: restart nginx
  service: name=nginx state=restarted
  sudo: yes

- name: restart supervisor
  service: name=supervisor state=restarted
  sudo: yes
